name: 🐞 Bug Report
description: Report a reproducible issue in the DevOpsCoin website, dApp, or ecosystem
title: '[Bug]: '
labels: ['bug']
projects: ['DevOpsCoin/core/roadmap']
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: 'Briefly describe the bug'
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to /fund
        2. Click 'Connect Wallet'
        3. Observe error
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: 'What should have happened?'
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: 'What actually happened?'
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: 'OS, Browser, Node version, pnpm version'
  - type: textarea
    id: logs
    attributes:
      label: Logs or Console Output
      render: shell
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched existing issues to avoid duplicates
          required: true
        - label: I can reproduce this issue consistently
          required: true
        - label: Includes relevant logs or screenshots
