# .github/ISSUE_TEMPLATE/roadmap_item.yml
name: '🗺️ Roadmap Item'
description: 'Add or track a roadmap task, feature, or improvement for DevOpsCoin.'
title: '[Roadmap] <Short description of item>'
labels:
  - roadmap
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the goal of this roadmap item.
      placeholder: e.g., Implement on-chain ledger sync for Ship-It Fund
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Current lifecycle state of the item.
      options:
        - Planned
        - In Progress
        - Under Review
        - Done
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Add any relevant links, context, or progress updates.
      placeholder: e.g., Linked PRs, design docs, repo paths, related discussions.
    validations:
      required: false

  - type: input
    id: suggested_labels
    attributes:
      label: Suggested Labels
      description: Optional — suggest labels that apply (e.g., frontend, docs, feature, shipit-fund).
      placeholder: e.g., feature, frontend, shipit-fund
    validations:
      required: false
