'use client';
import React from 'react';
import Link from 'next/link';

export default function ShipItFundPage() {
  return (
    <section className="relative max-w-4xl mx-auto mt-8 p-8 rounded-xl overflow-hidden text-left shadow-lg">
      {/* Background */}
      <div className="absolute inset-0">
        <div className="absolute inset-0 bg-gray-900" />
        <img
          src="/shipit/image1.png"
          alt="Ship It Fund Hero"
          className="absolute right-0 top-0 max-w-[50%] w-auto h-auto object-contain opacity-30 pointer-events-none select-none"
          aria-hidden="true"
        />
      </div>

      {/* Foreground */}
      <div className="relative" style={{ zIndex: 3 }}>
        {/* Title */}
        <h1 className="text-3xl sm:text-4xl font-bold text-cyan-400 mb-4 flex items-center gap-2">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="w-8 h-8 text-cyan-400"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 4v16m8-8H4"
            />
          </svg>
          Ship-It Fund
        </h1>

        {/* Mission */}
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-cyan-300 mb-2 flex items-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6 text-cyan-300"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 8v4l3 3"
              />
            </svg>
            Mission & Philosophy
          </h2>
          <p className="text-gray-300 text-lg mb-2">
            The <strong>Ship-It Fund</strong> is the heart of{' '}
            <strong>$DEVOPS</strong> — a community-driven pool designed to
            sustain both the <strong>builders</strong> who ship open-source
            innovation and the <strong>ecosystem</strong> that powers the token
            itself.
          </p>
          <p className="text-gray-400 italic">
            One fund, two missions — supporting DevOps culture while keeping the
            $DEVOPS economy healthy.
          </p>
        </section>

        {/* Funding Model */}
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-cyan-300 mb-2 flex items-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6 text-cyan-300"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 4v16M4 12h16"
              />
            </svg>
            Funding Model
          </h2>
          <ul className="list-disc pl-6 text-gray-300 space-y-2 mb-4">
            <li>
              <strong>Bootstrap allocation:</strong> 5% of total supply (50 M
              DEVOPS) is allocated to the Ship-It / Operations wallet at launch.
            </li>
            <li>
              <strong>Ongoing sustainability:</strong> Future funding comes from
              a portion of <strong>creator-reward inflows</strong> generated by
              $DEVOPS activity on pump.fun. There are no on-chain taxes or fees.
            </li>
            <li>
              <strong>Volume-based grants:</strong> If creator-reward volume
              falls below target in a given month, OSS grant payouts are{' '}
              <strong>deferred and rolled forward</strong> to maintain fiscal
              transparency.
            </li>
            <li>
              <strong>Transparency by design:</strong> All inflows, allocations,
              and disbursements are logged in the{' '}
              <a
                href="https://github.com/DevOpsCoin/shipit-fund/tree/main/ledger"
                target="_blank"
                rel="noopener noreferrer"
                className="text-cyan-400 underline"
              >
                public ledger
              </a>{' '}
              and verified on Solscan.
            </li>
          </ul>
          <p className="text-gray-400 text-sm italic">
            The fund begins with 5 % bootstrap liquidity — expanding organically
            as trading activity fuels creator-reward inflows.
          </p>
        </section>

        {/* Eligibility */}
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-cyan-300 mb-2 flex items-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6 text-cyan-300"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12l2 2l4 -4"
              />
            </svg>
            Who & What We Fund
          </h2>
          <p className="text-gray-300 mb-4">
            The Ship-It Fund backs individuals and small teams who embody DevOps
            culture — building automation, open tools, and experiments that help
            others ship faster.
          </p>
          <ul className="list-disc pl-6 text-gray-300 space-y-2">
            <li>Developer tooling and automation frameworks</li>
            <li>Open-source community infrastructure</li>
            <li>Educational labs and OSS training content</li>
            <li>Creative meme-tech or cultural projects with a DevOps twist</li>
          </ul>
        </section>

        {/* Transparency */}
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-cyan-300 mb-2 flex items-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6 text-cyan-300"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12l2 2l4-4"
              />
            </svg>
            Transparency & Tracking
          </h2>
          <p className="text-gray-300 mb-4">
            All Ship-It Fund activity is <strong>on-chain and public</strong>.
            Every grant, ecosystem payout, or liquidity move can be verified
            through{' '}
            <a
              href="https://solscan.io"
              target="_blank"
              rel="noopener noreferrer"
              className="text-cyan-400 underline"
            >
              Solscan
            </a>{' '}
            and mirrored in the{' '}
            <a
              href="https://github.com/DevOpsCoin/shipit-fund"
              target="_blank"
              rel="noopener noreferrer"
              className="text-cyan-400 underline"
            >
              Ship-It Fund GitHub repository
            </a>
            .
          </p>
          <p className="text-gray-400 text-sm">
            The same wallet fuels open-source work and reinforces $DEVOPS token
            health — full transparency, no off-chain reserves.
          </p>
        </section>

        {/* How to Apply */}
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-cyan-300 mb-2 flex items-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6 text-cyan-300"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 8v4l3 3"
              />
            </svg>
            Submit Your Project
          </h2>
          <p className="text-gray-300 mb-4">
            Have something worth shipping? Submit your open-source project
            proposal via GitHub. Submissions are reviewed transparently, and
            selected projects receive direct support from the Ship-It Fund.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a
              href="https://github.com/DevOpsCoin/shipit-fund/issues/new?assignees=&labels=submission&template=project_submission.yml"
              target="_blank"
              className="inline-block px-6 py-3 bg-cyan-600 text-white font-semibold rounded-lg shadow hover:bg-cyan-400 transition"
            >
              Submit via GitHub →
            </a>
            <a
              href="https://t.me/TheDevOpsCoin"
              target="_blank"
              className="inline-block px-6 py-3 bg-gray-800 text-cyan-300 font-semibold rounded-lg border border-cyan-700 hover:bg-gray-700 transition"
            >
              Chat with the Team
            </a>
          </div>
        </section>

        {/* Wallet Info */}
        <section className="container max-w-4xl mx-auto mt-8 p-4 bg-gray-800 rounded-lg text-center border border-cyan-700/40">
          <h2 className="text-2xl font-semibold text-cyan-300 mb-2 flex items-center justify-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6 text-cyan-300"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 8v8m0 0l-3-3m3 3l3-3"
              />
            </svg>
            Fund Wallet & Distributions
          </h2>
          <p className="text-gray-300">
            All distributions occur in{' '}
            <strong>$DEVOPS (Solana SPL token)</strong>. Recipients should use a
            Solana-compatible wallet such as{' '}
            <a
              href="https://phantom.app"
              target="_blank"
              className="underline text-cyan-400 hover:text-cyan-300"
            >
              Phantom
            </a>{' '}
            or{' '}
            <a
              href="https://solflare.com"
              target="_blank"
              className="underline text-cyan-400 hover:text-cyan-300"
            >
              Solflare
            </a>
            .
          </p>
          <p className="text-gray-400 text-sm mt-2">
            The Ship-It Fund address will be published at launch. All inflows
            and outflows remain verifiable on-chain.
          </p>
        </section>

        {/* Disclaimer */}
        <section className="mb-10 mt-8">
          <h2 className="text-2xl font-semibold text-yellow-400 mb-2 flex items-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6 text-yellow-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            Disclaimer
          </h2>
          <p className="text-gray-400 text-sm">
            The Ship-It Fund is a community initiative, not an investment
            vehicle. Funding is discretionary and depends on available
            creator-reward inflows. During months of low trading volume, grants
            may be paused and rolled forward transparently. No treasury, no
            reserve — one public wallet powering both the builders and the
            brand.
          </p>
        </section>

        {/* Nav */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center mt-8">
          <Link
            href="/"
            className="inline-flex items-center px-6 py-3 bg-cyan-700 text-white rounded-lg font-semibold shadow hover:bg-cyan-400 transition"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-5 h-5 mr-2 text-white"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <rect
                x="3"
                y="4"
                width="18"
                height="16"
                rx="2"
                className="fill-gray-800"
              />
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M8 4v4m8-4v4M3 10h18"
              />
            </svg>
            Back to Home
          </Link>
          <Link
            href="/whitepaper"
            className="inline-flex items-center px-6 py-3 bg-gray-800 text-cyan-300 font-semibold rounded-lg border border-cyan-700 hover:bg-gray-700 transition"
          >
            View Whitepaper →
          </Link>
        </div>
      </div>
    </section>
  );
}
