# docker-compose.yml
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - WATCHPACK_POLLING=true
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_TRADING_LIVE=${NEXT_PUBLIC_TRADING_LIVE}
      - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
    env_file:
      - .env.docker
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm dev

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env.docker
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: website_v2_postgres_data
